FROM maven

#coping src of your framework
COPY src /home/SeleniumTestFramework/src

#coping pom file of your framework
COPY pom.xml /home/SeleniumTestFramework

#coping testing.xml file of your framework
COPY testng.xml /home/SeleniumTestFramework

#running actual command
RUN mvn -f /home/SeleniumTestFramework/pom.xml clean test -DskipTests=true